linters-settings:
  depguard:
    list-type: denylist
    packages:
      # logging is allowed only by logutils.Log, 
      - github.com/sqljames/goalctl/logutils
    packages-with-error-message:
      - github.com/sqljames/goalctl/logutils: "logging is allowed only by logutils"
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845

  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/sqljames/goalctl
  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - strings.SplitN

  govet:
    check-shadowing: true
  lll:
    line-length: 180
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    #- deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    #- exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    #- gci
    #- gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    #- gofmt
    #- gofumpt
    - goheader
    #- goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    #- interfacebloat
    #- interfacer
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    #- nonamedreturns
    #- nosnakecase
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    #- reassign
    - revive
    #- rowserrcheck
    #- scopelint
    #- sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    #- usestdlibvars
    - varnamelen
    #- wastedassign
    - whitespace
    - wrapcheck
    - wsl
    # You can track the evolution of the generics support by following the 
    # https://github.com/golangci/golangci-lint/issues/2649.
    #- rowserrcheck # is disabled because of generics. 
    #- sqlclosecheck # is disabled because of generics.
    #- structcheck # is disabled because of generics.
    #- wastedassign # is disabled because of generics.



  ##disable-all: true
  ##enable:
  ##  - asciicheck
  ##  - bidichk
  ##  - bodyclose
  ##  - containedctx
  ##  - contextcheck
  ##  - cyclop
  ##  - decorder
  ##  - depguard
  ##  - dogsled
  ##  - dupl
  ##  - durationcheck
  ##  - errchkjson
  ##  - errcheck
  ##  - errname
  ##  - errorlint
  ##  - execinquery
  ##  - exportloopref
  ##  - funlen
  ##  - gochecknoinits
  ##  - goconst
  ##  - gocritic
  ##  - gocyclo
  ##  - gofmt
  ##  - goimports
  ##  - gomnd
  ##  - goprintffuncname
  ##  - gosec
  ##  - gosimple
  ##  - govet
  ##  - ineffassign
  ##  - lll
  ##  - misspell
  ##  - nakedret
  ##  - noctx
  ##  - nolintlint
  ##  - staticcheck
  ##  - stylecheck
  ##  - typecheck
  ##  - unconvert
  ##  - unparam
  ##  - unused
  ##  - whitespace

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - revive
  # - wsl

issues:
  fix: false

run:
  timeout: 10m
  skip-dirs:
    - vendor/

output:
  format: json